### ISSUE TITLE
ssh.wpengine.net vs ssh.wpengine.com

### ISSUE THREAD

**Issue by ankurk91** [wpengine/site-deploy#34]
**Describe the bug**
Failed to resolve host

### To reproduce
```yml
name: deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deployment:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_PRIVATE_KEY }} 
        WPE_ENV: 'testinggitedev'
```

### Expected behavior
It should connect to `ssh.wpengine.com` instead

### Build Output & Screenshots
```
Deploying your code to:
testinggitedev
setup ssh path
getaddrinfo testinggitedev.ssh.wpengine.net: Name does not resolve
```

### Version information
- Image version: latest
- Docker version: latest
- Operating system: ubuntu-latest

### Additional context
Why it connects to .net ?
